eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        payment:
          uri: http://payment-service/payment/doPayment
  order-service:
    endpoints:
      endpoint:
        order:
          uri: http://order-service/order/placeOrder
